---
abstract: 'CPAN Test Dummy that has multiple packages in one file with different versions'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::Test::Dummy::MultiPkgVer
name: CPAN-Test-Dummy-MultiPkgVer
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  CPAN::Test::Dummy::MultiPkgVer:
    file: lib/CPAN/Test/Dummy/MultiPkgVer.pm
    version: 0.01
  CPAN::Test::Dummy::MultiPkgVer::Inner:
    file: lib/CPAN/Test/Dummy/MultiPkgVer.pm
    version: 0.10
requires:
  perl: 5.8.1
resources:
  bugtracker: https://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer/issues
  homepage: https://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer.git
version: 0.01
